# -*- coding: utf-8 -*-
"""py06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xQ8pfuHURSyBHk41wzgk387n_eLrNDhB
"""

# files - data can be written, read and stored
#three modes- read, write, append mode

myfile=open("a.txt", "r")
print(myfile.read())

myfile.close()

myfile=open("a.txt","w")
myfile.write('this is written by programmer\n')

myfile=open("a.txt", "r")
print(myfile.read())

myfile=open("a.txt","a")
myfile.write('this is written by user\n')

myfile=open("a.txt", "r")
print(myfile.read())

# context manager
with open("a.txt", "r") as file1:
  print(file1.read())

print(file1.read())       # file closed automatically as it is not used currently

mylines=['Good evening\n', 'welcome back to class']
with open("a.txt", "w") as file:
  file.writelines(mylines)

myfile=open("a.txt", "r")
print(myfile.read())

#string formatting - formats selected part of string
# % operator
# .format()
# fstring
# string template class

print('hello %s all' % 'welcome')

print('hello %s all %s' % ('welcome\n', 'thank you'))

print('hello {1} {0} all ' .format('welcome\n', 'thank you'))

num=input('enter the value ')
num1=input('enter the value ')
print(f'the addition is {num+num1}')

a=10
b=10
print(f'the addition of 2 nos. is {a+b}')

